### ISSUE TITLE
relation "cv" does not exist

### ISSUE THREAD

**Issue by biobai** [lmb-embrapa/machado-docker#5]
Hi 
I am using machado-docker with docker-compose version 1.27.4, build 40524192, and got some errors as follows:

`$bash load_machadosample.sh`
```Preprocessing
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "cv" does not exist
LINE 1: ..."cv"."cv_id", "cv"."name", "cv"."definition" FROM "cv" WHERE...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/dist-packages/machado/management/commands/load_relations_ontology.py", line 51, in handle
    ontology = OntologyLoader(cv_name)
  File "/usr/local/lib/python3.6/dist-packages/machado/loaders/ontology.py", line 29, in __init__
    cv = Cv.objects.get(name=cv_name)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/dist-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "cv" does not exist
LINE 1: ..."cv"."cv_id", "cv"."name", "cv"."definition" FROM "cv" WHERE...
```
[error.txt](https://github.com/lmb-embrapa/machado-docker/files/5550639/error.txt)

**Comment by azneto** [comment]
It seems like the database was not created for some reason. Can you confirm the container called "machado_postgres" is up and running? 
If it's up and running, you should delete the file manage.py and the directory machadosample and try to run again. When there's no manage.py and the machadosample directory, the machado container will attempt to create the database from scratch. After that, you should be able to run the load_machadosample.sh script.

**Comment by azneto** [comment]
Fechando por inatividade.
